HIERARCHIAL CLUSTERING

K MEAN CLUSTERING

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
import numpy as np


In [ ]:
x=np.array([[1,2],[1,4],[1,0],[10,2],[10,5],[10,0]])

In [ ]:
kmeans=KMeans(n_clusters=2)

In [ ]:
model=kmeans.fit(x)

In [ ]:
pr=model.predict([[10,8]])

In [ ]:
pr

array([1], dtype=int32)

In [ ]:
model.labels_

array([0, 0, 0, 1, 1, 1], dtype=int32)

Knn classifier

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/diabetes (3).csv')

In [ ]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
x=df[['Glucose','BloodPressure','Insulin','BMI']]

In [ ]:
x.shape

(768, 4)

In [ ]:
y=df[['Outcome']]

In [ ]:
y

Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knc=KNeighborsClassifier(n_neighbors=5)

In [ ]:
knc_model=knc.fit(x_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [ ]:
pip install gTTS

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
text="Welcome to machine learning day 12"

In [ ]:
language='en'

In [ ]:
from gtts import gTTS

speech=gTTS (text=text,lang=language)

In [ ]:
speech.save("welcome.mp3")

KNN REGRESSION

In [ ]:
x=[[4],[5],[6],[7],[8]]
y=[35,45,62,71,86]

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
knr=KNeighborsRegressor(n_neighbors=3)

In [ ]:
knr_model=knr.fit(x,y)

In [ ]:
pr=knr_model.predict([[9]])

In [ ]:
pr

array([59.8])

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
dt=DecisionTreeRegressor()

In [ ]:
dt_model=dt.fit(x,y)

In [ ]:
pr=dt_model.predict([[9]])

In [ ]:
pr

array([86.])